# Generated by Django 2.2.24 on 2021-11-24 00:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='ISIN number must be 12 digits long and alphanumeric.', regex='^[a-zA-Z0-9]{12}$')])),
                ('size', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(140737488355328, message='Bond size cannot be larger than the market.')])),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Please enter a three-digit currency code.', regex='^[a-zA-Z]{3}$')])),
                ('maturity', models.DateField()),
                ('lei', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='LEI number must be 20 digits long and alphanumeric.', regex='^[a-zA-Z0-9]{20}$')])),
                ('legal_name', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
